name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
load: STARTUP
loadbefore: [Vault]
commands:
  permissions:
    description: "Access commands"
    aliases: [perms]
